version: '2'
services:
  apostol_api:
    container_name: apostol_api
    build: ./api
    environment:
      - CORS_FRONTEND_URL=https://beta.it-apostol.ru
      - DB_CONNECTION_URI=postgresql+psycopg2://apostol:apostol@apostol_base/apostol
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.apostol_api.rule=Host(`beta.it-apostol.ru`) && PathPrefix(`/api`, `/docs`, `/redoc`, `/openapi.json`)"
      - "traefik.http.routers.apostol_api.entrypoints=https"
      - "traefik.http.routers.apostol_api.tls=true"
      - "traefik.http.routers.apostol_api.tls.certresolver=letsencrypt"
      - "traefik.http.routers.apostol_api.middlewares=redirect-https"
      - "traefik.http.services.apostol_api.loadbalancer.server.port=8000"
    depends_on:
      - apostol_base

  apostol_front:
    container_name: apostol_front
    build: ./front
    environment:
      - REACT_APP_API_URL=https://beta.it-apostol.ru
      - PORT=80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.apostol_front.rule=Host(`beta.it-apostol.ru`)"
      - "traefik.http.routers.apostol_front.entrypoints=https"
      - "traefik.http.routers.apostol_front.tls=true"
      - "traefik.http.routers.apostol_front.tls.certresolver=letsencrypt"
      - "traefik.http.routers.apostol_front.middlewares=redirect-https"
      - "traefik.http.services.apostol_front.loadbalancer.server.port=80"
    depends_on:
      - apostol_api
  apostol_base:
    container_name: apostol_base
    image: postgres:13
    environment:
      - POSTGRES_DB=apostol
      - POSTGRES_USER=apostol
      - POSTGRES_PASSWORD=apostol
    volumes:
      - ./postgres:/var/lib/postgresql/data

    