import os
from loguru import logger
JWT_SECRET_KEY = os.environ.get('SECRET_KEY') or 'secret'
CORS_FRONTEND_URL = (os.environ.get('CORS_FRONTEND_URL') and os.environ.get('CORS_FRONTEND_URL').split()) or ['http://localhost:3000']
ACCESS_TOKEN_EXPIRE_SECONDS = (os.environ.get('ACCESS_TOKEN_EXPIRE_SECONDS') and int(os.environ.get('ACCESS_TOKEN_EXPIRE_SECONDS'))) or 24 * 60 * 60

logger.info('CORS_FRONTEND_URL: {CORS_FRONTEND_URL}', CORS_FRONTEND_URL=CORS_FRONTEND_URL)
logger.info('ACCESS_TOKEN_EXPIRE_SECONDS: {ACCESS_TOKEN_EXPIRE_SECONDS}', ACCESS_TOKEN_EXPIRE_SECONDS=ACCESS_TOKEN_EXPIRE_SECONDS)
logger.info('JWT_SECRET_KEY: {JWT_SECRET_KEY}', JWT_SECRET_KEY=JWT_SECRET_KEY)

